version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - labpro-net
      
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./dist/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
    networks:
      - labpro-net

networks:
  labpro-net:
    name: "labpro-network"